# fly.toml app configuration file generated for open-hivemind on 2025-01-17T22:46:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'open-hivemind'
primary_region = 'syd'

[build]
  image = 'mhand79/open-hivemind'
  [build.args]
    BUILD_TIMESTAMP = "1736856000"

[env]
  PORT = '5005'

[http_service]
  internal_port = 6000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1 
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
